version: '3.5'
services:

  mysql:
    image: 'mysql:5.6'
    ports:
     - '3306'
    volumes:
     - .:/opt
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=app
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=password
    networks:
     - proxynet

  redis:
    image: 'redis:4'
    networks:
     - proxynet

  web: &web
    image: joesweeny/back_to_win_api_web_staging:latest
    environment:
     - ADMIN_BANK_DRIVER=redis
     - AUTH_TOKEN_DRIVER=jwt
     - BANK_DRIVER=redis
     - DB_DSN=mysql:host=mysql;dbname=app
     - DB_USER=root
     - DB_PASSWORD=password
     - ENTRY_FEE_STORE_DRIVER=redis
     - JWT_SECRET=t9BBDNMYwbN634AJrXv0
     - LOG_LOGGER=monolog
     - STORAGE_DRIVER=aws
    networks:
     - proxynet

  migrate:
    <<: *web
    command: /opt/bin/migrate
    restart: on-failure

networks:
  proxynet:
    name: back_to_win_api_network
