version: '3.3'
services:

  mysql:
    image: 'mysql:5.6'
    ports:
     - '3306'
    volumes:
     - .:/opt
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=app
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=password

  redis:
    image: 'redis:4'

  nginx-proxy:
    build:
      dockerfile: ./docker/nginx-proxy/Dockerfile
      context: ./
    ports:
      - "80"
      - "443"
    links:
      - web

  web: &web
    build:
      dockerfile: ./docker/web/Dockerfile
      context: ./
    links:
     - mysql
    environment:
     - ADMIN_BANK_DRIVER=redis
     - AUTH_TOKEN_DRIVER=jwt
     - BANK_DRIVER=redis
     - DB_DSN=mysql:host=mysql;dbname=app
     - DB_USER=root
     - DB_PASSWORD=password
     - ENTRY_FEE_STORE_DRIVER=redis
     - JWT_SECRET=t9BBDNMYwbN634AJrXv0
     - LOG_LOGGER=monolog
    volumes:
     - .:/opt

  migrate:
    <<: *web
    restart: on-failure
    command: /opt/bin/migrate

  test:
    build:
      dockerfile: ./docker/web/Dockerfile
      context: ./
    links:
     - mysql
    environment:
     ADMIN_BANK_DRIVER: log
     AUTH_TOKEN_DRIVER: jwt
     BANK_DRIVER: log
     DB_DSN: "sqlite::memory:"
     DB_USER: root
     DB_PASSWORD: password
     ENTRY_FEE_STORE_DRIVER: log
     JWT_SECRET: t9BBDNMYwbN634AJrXv0
     LOG_LOGGER: monolog
    volumes:
     - .:/opt
