version: '2'
services:

  php:
    image: joesweeny/game_platform_php_staging:latest
    environment:
     - ADMIN_BANK_DRIVER=redis
     - AUTH_TOKEN_DRIVER=jwt
     - BANK_DRIVER=redis
     - DB_DSN=mysql:host=mysql;dbname=app
     - DB_USER=root
     - DB_PASSWORD=password
     - ENTRY_FEE_STORE_DRIVER=redis
     - JWT_SECRET=t9BBDNMYwbN634AJrXv0
     - LOG_LOGGER=monolog

  mysql:
    image: 'mysql:5.6'
    ports:
     - '3306:3306'
    volumes:
     - .:/opt
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=app
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=password

  redis:
    image: 'redis:4'