version: '2'
services:

  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
    environment:
     - ADMIN_BANK_DRIVER=log
     - BANK_DRIVER=log
     - DB_DSN=mysql:host=mysql;dbname=app
     - DB_USER=root
     - DB_PASSWORD=password
     - ENTRY_FEE_STORE_DRIVER=log
     - LOG_LOGGER=monolog
    volumes:
     - .:/opt

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: ./
    ports:
     - "80"
    volumes:
     - .:/opt
    links:
     - php

  mysql:
    image: 'mysql:5.6'
    ports:
     - '3306:3306'
    volumes:
     - .:/opt
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=app
     - MYSQL_USER=dev
     - MYSQL_PASSWORD=password

  redis:
    image: 'redis:4'

