version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-apache-stretch-node-browser

    steps:
      - checkout
      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web bash /opt/bin/test