version: 2
jobs:
  build:
    working_directory: ~/gameplatform
    machine:
      image: circleci/classic:201711-01

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install php7.2
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - run:
          name: Build Release Image
          command: |
            composer install --ignore-platform-reqs --no-dev --optimize-autoloader
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Test Release Image
          command: |
            composer install --ignore-platform-reqs
            docker-compose -f docker-compose.yml run web docker/wait-for-it.sh mysql:3306 -t 90
            docker-compose -f docker-compose.yml run web src/vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 src/app/
            docker-compose -f docker-compose.yml run --rm test bash /opt/bin/test

      - deploy:
          name: Deploy to Staging/Production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod +x ./.circleci/staging/docker-push.sh
              ./.circleci/staging/docker-push.sh
              chmod +x ./.circleci/staging/docker-deploy.sh
              ./.circleci/staging/docker-deploy.sh
            fi