openapi: 3.0.0
info:
  title: Game Platform API
  version: 1.0.0
servers:
  - url: https://api-staging.joesweeny.co.uk
    description: Staging Environment

paths:
  /api/user:
    post:
      description: Create a new User for this application
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: joesweeny
                email:
                  type: string
                  example: joe@joe.com
                password:
                  type: string
                  example: myreallycomplicatedpassword!@woo
                currency:
                  type: string
                  example: 'FAKE'

      responses:
        '200':
          description: Response containing data of newly created User
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'

        '400':
          description: 'The request sent was incorrectly formatted'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailResponse'

        '422':
          description: 'Unable to create resource with properties provided in request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailResponse'

        '500':
          description: 'Server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


    get:
      description: Get an array of all Users registered to this application
      tags:
        - User
      responses:
        '200':
          description: An array of all Users registered to this application
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Uuid'
        username:
          type: string
          example: joesweeny
        email:
          type: string
          example: joe@joe.com
        created_at:
          $ref: '#/components/schemas/Date'
        updated_at:
          $ref: '#/components/schemas/Date'


    Uuid:
      type: string
      description: UUID string using the v4 specification
      example: 'd3562005-4598-4e4e-9149-3d12ed58e14f'

    Date:
      type: string
      description: A date formatted to ISO 8601 specification
      example: '2018-03-12T15:00:00+00:00'

    FailResponse:
      type: object
      properties:
        status:
          type: string
          example: 'fail'
        data:
          type: object
          properties:
            errors:
              type: array
              items:
                $ref: '#/components/schemas/JsendError'

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: 'error'
        data:
          type: object
          properties:
            errors:
              type: array
              items:
                $ref: '#/components/schemas/JsendError'

    JsendError:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
          example: 'Something went wrong'
        code:
          type: integer
          example: 1
          description: >-
            A code to identify the error. "1" is used when no specific error code has been defined for this error

security:
  - bearerAuth: []