FROM nginx:1

ADD ./docker/nginx-proxy/certs/localhost.crt /etc/nginx/ssl/localhost.crt
ADD ./docker/nginx-proxy/certs/localhost.key /etc/nginx/ssl/localhost.key
ADD ./docker/nginx-proxy/nginx.conf /etc/nginx/nginx.conf
